name: Submodule Update

permissions:
  contents: write 
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  submodule-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          submodules: true
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update submodules
        shell: bash
        run: git submodule update --remote
      - name: Create and checkout new branch
        id: branch
        shell: bash
        run: |
          BRANCH="chore/submodule-update-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH"
          echo "$BRANCH=BRANCH" >> "$GITHUB_OUTPUT"
      - name: Commit and push changes
        shell: bash
        run: |
          git commit -am "Updated submodules"
          git push --set-upstream origin '${{ steps.branch.outputs.BRANCH }}'
      - name: Create pull request
        uses: actions/github-script@v9.0.0
        with:
          script: |
            await github.rest.pulls.create({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.repository }}'.split('/')[1].trim(),
              head: '${{ steps.branch.outcome.BRANCH }}',
              base: 'main',
            });
