name: Submodule Update

permissions:
  contents: write 
  pull-requests: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  submodule-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          submodules: true
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update submodules
        id: update
        shell: bash
        run: |
          git submodule update --remote
          set +e
            git diff --quiet; echo "DIFF=$?" >> $GITHUB_OUTPUT
          set -e
      - name: Create and checkout new branch
        if: steps.update.outputs.DIFF==1
        id: branch
        shell: bash
        run: |
          BRANCH="chore/submodule-update-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH"
          echo "BRANCH=$BRANCH" >> "$GITHUB_OUTPUT"
      - name: Commit and push changes
        if: steps.update.outputs.DIFF==1
        shell: bash
        env:
          BRANCH: ${{ steps.branch.outputs.BRANCH }}
        run: |
          git commit -am "Updated submodules"
          git push --set-upstream origin "$BRANCH"
      - name: Create pull request
        if: steps.update.outputs.DIFF==1
        uses: actions/github-script@v9.0.0
        env:
          BRANCH: ${{ steps.branch.outputs.BRANCH }}
        with:
          script: |
            await github.rest.pulls.create({
              owner: "${{ github.repository_owner }}",
              repo: "${{ github.repository }}".split("/")[1].trim(),
              head: "${{ env.BRANCH }}",
              base: "main",
              title: "Update submodules"
            });
